### ISSUE TITLE
Hosting craftycomponents.com

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#529]
What to do with craftycomponents.com?

**Comment by potomak** [comment]
If http://craftyjs.com is out of date then what about http://craftycomponents.com ?

**Comment by starwed** [comment]
Regarding _craftyjs.com_: That's the one hosted on github, corresponding to [the craftyjs.github.com repo](https://github.com/craftyjs/craftyjs.github.com).  I don't see any recent issues/comments, so how is it out of date?  (I don't have the permissions to accept stuff into that repo, but @louisstow  has done that when it was time for a release.)

Regarding _craftycomponents.com_: I have no idea what's going on with it!  Whoever maintains it has fixed the occasional issue that's cropped up, but they haven't come forward and I have no idea how to contact them.

**Comment by sbyrnes321** [comment]
About craftycomponents: See previous discussion -- https://groups.google.com/d/msg/craftyjs/VWmegaSP7B4/aAZYV3A6hbcJ

**Comment by starwed** [comment]
@ahilles107 seems to be his github tag, so hopefully he'll now get notified about this issue?  :)

**Comment by ahilles107** [comment]
Hey, http://craftycomponents.com/ looks bad now because twitter bootstrap cdn for 1.4 is gone, i don't have now a lot of time for crafty, if you wan't take http://craftycomponents.com to your server then just just email me.

**Comment by kevinsimper** [comment]
I got confused with this repo https://github.com/craftyjs/craftyjs.com

There is game at the bottom which gives 404, and the link to the minified version gives also a 404, but i have created a issue there.

**Comment by starwed** [comment]
Probably worth figuring out if craftycomponents needs to be a dynamic site, or whether we can host it on github along with craftyjs.com.  (I went ahead and repurposed & reopened this issue)

@ahilles107 Does the [craftycomponents repo](https://github.com/craftyjs/CraftyComponents) reflect what was actually on the site?  (And thanks for hosting it so far!)

**Comment by kevinsimper** [comment]
@starwed It could be hosted at Github, but the dynamic stored made with Firebase.io. It could also be Parse.com.

I have written to Louis and asked if i can help with crafty.github.com :-)

**Comment by kevinsimper** [comment]
I have written to achilles107 about the domain, I will try to get the website up and running again!

**Comment by kevinsimper** [comment]
@ahilles107 Hi, have you been busy? :)

**Comment by potomak** [comment]
Any news about this issue?
@ahilles107 are you going to give access to https://github.com/craftyjs/CraftyComponents to @kevinsimper?
Can I help in any way?

See also https://groups.google.com/d/topic/craftyjs/fPAjmPel-aE/discussion

**Comment by kevinsimper** [comment]
@potomak I have tried getting in touch with him but without luck.

We should find out something new, Craftycomponents is also rather long :-)

**Comment by potomak** [comment]
I think http://components.craftyjs.com would be fine.

Now we only need access to the repo, we could create a static github page using the `gh-pages` branch.

TODO:
- [ ] set CNAME components.crafty.com, see https://help.github.com/articles/setting-up-a-custom-domain-with-pages
- [ ] give access to https://github.com/craftyjs/CraftyComponents to @kevinsimper (and me if you want help)
- [ ] set up a `gh-pages` branch

**Comment by kevinsimper** [comment]
@potomak They way it is made now, there has be to a server, but Nodejitsu gives free server hosting to open source projects, so that would be great.

They way it works now is that whoever makes a component and want to share it, puts a speciel url into the post-hook field on github, so that the components website is let now that there is a new version. So gh-pages would not work.

**Comment by potomak** [comment]
Ok, sorry I didn't know about the dynamic nature of craftycomponents.com.

There are two options:
1. ask Nodejitsu for free hosting due to the open source nature of the project
2. set it up as a static site

I think that the first option is less time consuming since the project is already done.

**Comment by potomak** [comment]
@kevinsimper it's a Symfony app, Nodejitsu hosts Node.js apps.

**Comment by ahilles107** [comment]
@potomak -  https://github.com/craftyjs/CraftyComponents is in craftyjs organization - so everyone from organization have access there. 

If you want then i can change dns on domain, and later transfer it for someone else.

**Comment by potomak** [comment]
@ahilles107 I'm not an organization member right now, I hope I will.

I'll work on my fork asap to let it work as a node.js app (javascript even for server side for a javascript framework is the right choice in my opinion).

Thanks for your response anyway.

**Comment by kevinsimper** [comment]
@potomak I would also think a Node.js app would be the best choice. That would make it easier to contribute to if you already know javascript.
Then Nodejitsu is also the obivious choice because of the free hosting.

**Comment by potomak** [comment]
I totally agree @kevinsimper

**Comment by starwed** [comment]
I guess we should do something about this, since the site looks pretty bad right now!

A three step plan:
- [ ] Get a skeletal node app working that replaces the current site's back end functionality
- [ ] Design a front-end website
- [ ] Ask nodejitsu about [free hosting](http://opensource.nodejitsu.com/)

**Comment by potomak** [comment]
I successfully deployed version 0.0.1 of the new Crafty Components site, see http://crafty-components.jit.su/
There's a lot more to do but I think we could start by adding a CNAME at components.craftyjs.com (@louisstow) or at craftycomponents.com (@ahilles107) that links to crafty-components.jit.su.

The new Crafty Components is much more simpler, it relies on webhooks (it works only with github webhooks now) to get informations about the component reading a file `component.json`, see documentation at https://github.com/potomak/CraftyComponents#componentjson.

The idea is to use npm in conjunction with browserify to load and use crafty components, this is what they're doing at voxel and I think it's the best way to handle javascript requirements. Note that with this in mind we could just use the `package.json` to grab informations about components instead of `component.json`.

**Comment by kenbellows** [comment]
Has there been any recent activity on getting the components available again? Currentl @potomak's site says it has no components in the index. Can we get access to them some way or another, even jsut to download and use locally?

**Comment by kenbellows** [comment]
Short term, I've found that archive.org has a mirror from before the old site went down and it seems to still work okay. https://web.archive.org/web/20130704224536/http://craftycomponents.com/

If you guys would like some help, I'm willing to contribute to get this guy up and running again. Or is it just a matter of submitting the components again?

**Comment by potomak** [comment]
@kenbellows you could add PR to old components to make them discoverable in the new components site. See https://github.com/craftyjs/CraftyComponents#how-does-it-work

**Comment by kevinsimper** [comment]
We have created a component section on the craftyjs.com website :)
