### ISSUE TITLE
CI with testling-ci

### ISSUE THREAD

**Issue by potomak** [craftyjs/Crafty#581]
To do:
- [ ] update package.json (see http://ci.testling.com/#package.json)
- [ ] update tests to produce TAP output using https://github.com/substack/tape (see http://ci.testling.com/#write)
- [ ] add a webhook to http://git.testling.com (see http://ci.testling.com/#hook)
- [ ] add badge in README.md (see http://ci.testling.com/#badge)

See also #540

**Comment by kenany** [comment]
Looks like QUnit can use a [plugin](https://github.com/twada/qunit-tap) to produce TAP output. Might be easier than converting over to tape (don't get me wrong, I love tape).

**Comment by mucaho** [comment]
@starwed and @sorenbs have owner rights now. They can add the webhook.

If either of you two (potomak/KenanY) feel up for it, you can go ahead and start coding :)

**Comment by kevinsimper** [comment]
@mucaho Yes, that is a start, but the test has to be converted from QUnit to either Mocha and Tape before we can use Testling. (sorenbs has been inactive for a long time unfortunatly).

**Comment by mucaho** [comment]
@kevinsimper Can't we use the [Qunit TAP plugin](https://github.com/twada/qunit-tap) as suggested by KenanY? No need to convert any test, just some preprocessing/postprocessing, right?

**Comment by mucaho** [comment]
There is another alternative called [Sauce Labs](https://saucelabs.com/opensauce/), which is also free for OSS. [Rumored](https://github.com/Financial-Times/ft-origami/issues/218) to be faster than testling.

EDIT:
Yes, testling is effectively [down](https://github.com/substack/testling/issues/88#issuecomment-67369563). The required modifications to the source files (if testling will work again) can be found in my [testling branch](https://github.com/mucaho/Crafty/commit/1f4104e8e112138dd1cf01f4b3d147c25bd64d75)

EDIT2:
Found alternative [zuul](https://github.com/defunctzombie/zuul#cross-browser-testing-via-saucelabs). It works out of the box with `qunit`, and runs the cross-browser tests in sauce labs, after it is initiated on travis ci through a new build.

EDIT3:
Zuul would be quite complicated to integrate with grunt. Luckily there is [`grunt-saucelabs`](https://github.com/axemclion/grunt-saucelabs#integration-with-a-ci-system) - a grunt plugin that we can use to run the tests on sauce labs servers (be it from a local initiated test run or by travis initiated test run)

**Comment by mucaho** [comment]
Implemented alternative cross-browser compatibility tests via Sauce Labs in #927.
