### ISSUE TITLE
Documentation tracking bug

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#675]
I noticed several issues in the documentation, thought having a single issue to track this would be a good idea.  Includes both errors in the raw docblocks and the parser.
- [x] Crafty.modules should mention that there are issues with the components site. ([potomak's comment](https://github.com/craftyjs/Crafty/pull/674#issuecomment-31336075))
- [x] The SaveData and LoadData events aren't documented in the standard way.  (Storage component.)
- [x] Crafty.extend has basically no documentation (core.js)
- [ ] Several of the docblocks in HashMap.js aren't being parsed?
- [x] Crafty.isometric.centerAt missing docs for parameters
- [x] The stuff in math.js apparently was assuming a different docblock style than the rest of the codebase -- there are tons of issues there.
- [x] Color example syntax error.
- [x] Fix "TweenEnd" event argument documentation, as described in forum https://groups.google.com/d/msg/craftyjs/CQrV_STfs84/kaPmsNrrAAAJ
- [x] Add "properties" shorthand (introduced in #1096) to [component documentation](http://craftyjs.com/documentation/components.html).

Random thoughts
- We use triple tilde for codeblocks; it might be nicer to use triple backticks like github does?  Also, syntax highlighting for codeblocks would make everything look a lot better.
